config/routes.rb
Rails.application.routes.draw do
    resources :stocks do
       collection { post :import } 
    end
    resources :contacts
    root 'homepages#index'
    
    get "signup", to: "users#new"
    resources :users, except: [:new]
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    post 'comments', to:'comments#create'
    resources :comments, except: [:create, :edit, :new, :index]
    
    namespace :admin do
        get 'users',to: 'users#index'
    end

end

app/models/stock.rb
class Stock < ActiveRecord::Base
    default_scope { order('created_at ASC') }
    belongs_to :user
    validates :barcode, :name, :description, presence: true 
    validates :barcode, uniqueness: true
    validates :quantity, :price, presence: true
    validates :user_id, presence: true

    def self.search(search)
        if search
            where("name LIKE :search OR description LIKE :search",search: "%#{search}%") 
            #where("description LIKE ?", "%#{search}%")
         end
    end
    
    def self.import(file, user)
        count = 0
        CSV.foreach(file.path, headers: true) do |row|
           new_stock = Stock.create row.to_hash
           new_stock.user = user
           if !new_stock.save
               count +=1
           end
        end
        return true, count
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
   before_action :set_stock, only: [:show, :edit, :update, :destroy]
   before_action :require_user
   before_action :require_same_user, only: [:show, :edit, :update, :destory]
   
   def index
      @stock = Stock.new
      if params[:search]
         @stocks = current_user.stocks.search(params[:search]).paginate(page: params[:page], per_page: 20)
      else
         @stocks = current_user.stocks.paginate(page: params[:page], per_page: 20)
      end
      
   end
   
   def new
      @stock = Stock.new
   end
   
   def create
      @stock = Stock.new(stock_params)
      @stock.user = current_user
      if @stock.save 
         flash[:success] = 'Stock was successfully added'
         redirect_to stocks_path
      else
         @stocks = current_user.stocks.paginate(page: params[:page], per_page: 20)
         render 'index'
      end
   end
   
   
   def show

   end
   
   def edit

   end
   
   def update

      if @stock.update(stock_params)
         flash[:success] = 'Stock successfully updated'
         redirect_to stocks_path
      else
         render 'edit'
      end
   end
   
   def destroy
 
      @stock.destroy
      flash[:danger] = 'Stock successfully removed'
      redirect_to stocks_path
   end
   
   def import
      status, count = Stock.import(params[:file], current_user)
      if status && count == 0
         flash[:success] = 'File successfully updated'
         redirect_to stocks_path
      else
         flash[:danger] = "File did not upload \n A total of #{count} rows unsuccessfully uploaded"
         redirect_to stocks_path
      end
   end
   
   private
   def stock_params
      params.require(:stock).permit(:barcode, :name, :description, :quantity, :price)
   end
   
   def set_stock
       @stock = Stock.find(params[:id])
   end
   
   def require_same_user
     return if logged_in? && (current_user?(@stock.user) || current_user.admin?)
         flash[:danger] = "You can only edit or delete your own stocks"
         redirect_to root_path
      end
   
end

app/views/stocks/_dropdownbutton.html.erb
<div class="dropdown center">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    &#2506;
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to 'Edit', edit_stock_path(stock) %></li> 
    <li role="separator" class="divider"></li>
    <li><%= link_to 'Delete', stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'} %></li>
  </ul>
</div>

app/views/stocks/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
<div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
        <div class="panel-heading">
        <div class="panel-title">
            <h4>The following <%= pluralize(obj.errors.count, "error") %> occured:</h4>
        <div class="panel-body">
            <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        </div>
        </div>
    </div>
</div>
</div>    
<% end %>

app/views/stocks/_form.html.erb
<div class='containner'>
    <div class='row'>
        <div class='col-xs-12'>
 
            <%= form_for(@stock, :html => {class: "form-horizontal", role: "form"}) do |f| %>
                <div class='form-group'>
                    <div class="control-label col-sm-2">
                    <%= f.label :barcode %></br>
                    </div>
                    <div class='col-sm-4'>
                    <%= f.text_field :barcode, class: "form-control", placeholder: "Enter Barcode", autofocus: true, id: 'stock_barcode' %>
                    </div>
                </div>
                <div class='form-group'>
                    <div class="control-label col-sm-2">
                    <%= f.label :name %> </br>
                    </div>
                    <div class='col-sm-4'>
                    <%= f.text_field :name, class: "form-control", placeholder: "Enter Stock Name" %>
                    </div>
                </div>
                <div class='form-group'>
                    <div class="control-label col-sm-2">
                    <%= f.label :description %></br>    
                    </div>
                    <div class='col-sm-4'>
                    <%= f.text_field :description, class: "form-control", placeholder: "Enter Description of Stock e.g. 10/0" %>
                    </div>
                </div>
                <div class='form-group'>
                    <div class="control-label col-sm-2">
                    <%= f.label :quantity %></br>
                    </div>
                    <div class='col-sm-4'>
                    <%= f.number_field :quantity, :value => 0, class: "form-control", placeholder: "Enter quantity" %>
                    </div>
                </div>
                <div class='form-group'>
                    <div class="control-label col-sm-2">
                    <%= f.label :price %></br>
                    </div>
                    <div class='col-sm-4'>
                    <%= f.text_field :price, :value => 0, class: "form-control", placeholder: "Enter price e.g 10.10" %>
                    </div>
                </div>
                <div class='form-group'>
                    <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit 'Add Stock',  class: "btn btn-primary btn-lg" %>
                    </div>
                </div>
                
            <% end %>
        </div>
    </div>
</div>

app/views/stocks/_lookup.html.erb
<div id='stock-lookup'>
    <%= form_tag stocks_path, remote: false, method: :get, id: 'stock-lookup-form' do %>
        <div class="form-group no-padding text-center">
            <div class="col-md-6">
                <%= text_field_tag :search, params[:search], placeholder: "Stock description or name", autofocus: true,
                                                        class: "form-control search-box input-md" %>
            </div>
            <div class="col-md-2">
                <%= button_tag(type: :submit, class: "btn btn-md btn-success") do %>
                    <i class="fa fa-search"></i> Lookup a stock
                <% end %>
            </div>
        </div>     
    <% end %>
</div>

app/views/stocks/edit.html.erb
<div align='center'><h1>Edit stocks<</h1></div>

<%= render 'errors', obj: @stock %>



<div class='well'>
<div class='row'>
<div class='col-sm-offset-4'>
<%= render 'form' %>
</div>
</div>
</div>


<%= link_to 'Return to stock listing', stocks_path, class: 'btn btn-lg btn-danger' %>

app/views/stocks/index.html.erb
<div class="container">
    <h1 class = 'center'>Stock List</h1>
    <%= render 'errors', obj: @stock %>
    
    <div class="row">
        <%= render 'lookup' %>
        <div class='col-md-2 col-md-offset-2'>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">New Stock</button>
            
            <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
              <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class='modal-header'>
                            Create New Stocks
                        </div>
                        <div class='modal-body'>
                            <div class='container'>
                                <%= render 'form' %>
                            </div>
                        </div>
                        <div class="modal-footer">
                           <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
              </div>
            </div>
        </div>
    </div>
            
    <hr>
    <!--Stocks table begin-->
    <div class='row'>
        <div class='col-md-12'>
            <div class= "panel panel-default">
                 <div class="panel-body">
                    <table class="table center">
                        <thead>
                            <tr>
                                <th class="col-md-2 center">Barcode</th>
                                <th class="col-md-3 center">Name</th>
                                <th class="col-md-4 center">Description</th>
                                <th class="col-md-1 center">Qty</th>
                                <th class="col-md-1 center">Price</th>
                                <th class='center col-md-1'>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @stocks.each do |stock| %>
                            <div id='stock-lookup-results' %>
                                <tr>
                                    <td>
                                        <%= stock.barcode %>
                                    </td>
                                    <td>
                                        <%= stock.name %>
                                    </td>
                                    <td>
                                        <%= stock.description %>
                                    </td>
                                    <td>
                                        <%= stock.quantity %>
                                    </td>
                                    <td>
                                        <%= stock.price %>
                                    </td>
                                    <% if logged_in? && (current_user?(stock.user) || current_user.admin?) %>
                                    <td>
                                        <%= render 'dropdownbutton', stock: stock %>
                                    </td>
                                    <% end %>
                                </tr>
                            <% end %>
                            </div>
                        </tbody>
                    </table>
                    <div align='center'>
                        <%= will_paginate %>
                    </div>
                </div>
           </div>
        </div>
    </div>
    <!--Stocks table end-->
    
    <hr>
    <!--Import csv file button-->
    <div class='row'>
        <div class='col-xs-2 col-xs-offset-10'>
            <button type='button'class='btn btn-primary' data-toggle='modal' data-target='.file_upload'>Upload</button>
            <div class="modal fade file_upload" tabindex="-1" role="dialog" aria-labelledby="FILEUPLOAD">
                  <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class='modal-header'>
                                Upload Stocks From File
                            </div>
                            <div class='modal-body'>
                                <div class='container'>
                                    <%= form_tag import_stocks_path, multipart: true do %>
                                      <%= file_field_tag :file %>
                                      <%= submit_tag "Import" %>
                                    <% end %>
                                </div>
                            </div>
                            <div class="modal-footer">
                               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                  </div>
            </div>
        </div>
    </div>
    <!--File upload end-->
    
</div>

app/views/stocks/new.html.erb
<div class='center'><h1>Creating new Stocks</h1></div>
<hr>
<%= render 'errors', obj: @stock %>

<%= render 'form' %>

<%= link_to "All stocks", stocks_path %>