config/routes.rb
Rails.application.routes.draw do
    resources :stocks do
       collection { post :import } 
    end
    resources :contacts
    root 'homepages#index'
    
    get "signup", to: "users#new"
    resources :users, except: [:new]
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    post 'comments', to:'comments#create'
    resources :comments, except: [:create, :edit, :new, :index]
    
    namespace :admin do
        get 'users',to: 'users#index'
    end

end

app/views/layouts/_messages.html.erb
<div class="row">
<div class='col-xs-10 col-xs-offset-1'>

<% flash.each do |name, msg| %>
    <div class='alert alert-<%= "#{name}" %>'>
        <a href='#' class='close' data-dismiss='alert'>&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
<% end %>

</div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'StockTake', root_path, id: 'logo' %>
    </div>
    
    <% if logged_in? %>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li><a href="#">Link<span class="sr-only">(current)</span></a></li>-->
        <!--<li><a href="#">Link</a></li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Stock <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Stock List', stocks_path %></li>
            <li><a href="#">Stock Take</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Invoce</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contacts <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Contacts List', contacts_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'New Contact', new_contact_path %></li>
          </ul>
        </li>
      </ul>
      
      <% end %>
      
      <ul class="nav navbar-nav navbar-right">
        <% if !logged_in? %>
        <li> <%= link_to "Sign Up", signup_path %>  <li>
        <li> <%= link_to 'Sign in', login_path %> </li>
        <% end %>
        
        <% if logged_in? %>
            
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
              <% if current_user.admin? %>
              <li> <%= link_to 'Administration', admin_users_path %> </li>
              <% end %>
              <li> <%= link_to 'Logout', logout_path, method: :delete %>
          </li>
        <% end %>
          
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<div class="container" >
<%= render 'layouts/messages' %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>


</body>
</html>